### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Interface "Hyperf\Contract\CanBeEscapedWhenCastToString" not found 

### ISSUE THREAD

**Issue by cokeTsang** [hyperf/collection#3]
一个线上项目更新后执行`php bin/hyperf.php`失败
composer.json里面写的是"hyperf/config": "~3.1.0"
更新后执行出现这个错误
```
PHP Fatal error:  Uncaught Error: Interface "Hyperf\Contract\CanBeEscapedWhenCastToString" not found in /home/wwwroot/ad_project_process/vendor/hyperf/collection/src/Collection.php:39
Stack trace:
#0 /home/wwwroot/ad_project_process/vendor/composer/ClassLoader.php(571): include()
#1 /home/wwwroot/ad_project_process/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 /home/wwwroot/ad_project_process/vendor/hyperf/collection/src/Functions.php(28): Composer\Autoload\ClassLoader->loadClass()
#3 /home/wwwroot/ad_project_process/vendor/hyperf/support/src/Composer.php(45): Hyperf\Collection\collect()
#4 /home/wwwroot/ad_project_process/vendor/hyperf/support/src/Composer.php(95): Hyperf\Support\Composer::getLockContent()
#5 /home/wwwroot/ad_project_process/vendor/hyperf/config/src/ProviderConfig.php(37): Hyperf\Support\Composer::getMergedExtra()
#6 /home/wwwroot/ad_project_process/vendor/hyperf/di/src/Annotation/ScanConfig.php(106): Hyperf\Config\ProviderConfig::load()
#7 /home/wwwroot/ad_project_process/vendor/hyperf/di/src/Annotation/ScanConfig.php(86): Hyperf\Di\Annotation\ScanConfig::initConfigByFile()
#8 /home/wwwroot/ad_project_process/vendor/hyperf/di/src/ClassLoader.php(50): Hyperf\Di\Annotation\ScanConfig::instance()
#9 /home/wwwroot/ad_project_process/bin/hyperf.php(31): Hyperf\Di\ClassLoader::init()
#10 /home/wwwroot/ad_project_process/bin/hyperf.php(37): {closure}()
#11 {main}
  thrown in /home/wwwroot/ad_project_process/vendor/hyperf/collection/src/Collection.php on line 39
```

强制降版本后就能执行成功了
`composer require hyperf/collection v3.1.35`

**Comment by limingxinleo** [comment]
别用国内镜像源，另外线上项目不要直接操作 composer update 之类的。

要在本地 composer update -oW

然后线上要 composer install

这个情况是你 hyperf/contract 没有更新到最新导致的
